### ISSUE TITLE
Validation group not listed for vote revoking or unlocking coins

### ISSUE THREAD

**Issue by submetropolis** [jmrossy/celo-web-wallet#131]
Validation group starting with 0XDaDbd6 can not be found in the dropdown or searchable in the list of groups. I have 9134.894 locked in with this group and am unable to revoke votes or unstake. Please help
![Celo](https://github.com/user-attachments/assets/34af52af-73b8-4ac9-a171-77a7f5153c7e)

**Comment by jmrossy** [comment]
@submetropolis this wallet is no longer receiving feature updates, only critical security fixes.
To unstake your funds, you can use https://mondo.celo.org which is the new recommended tool for staking and governance on Celo

**Comment by submetropolis** [comment]
Ok, I clicked the link. Do I need to setup a new wallet, connect one or ?
Zero instructions on what I'm supposed to do?
